name: Generate ascii artwork

on: 
  push:

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay (DRAGON)
        run: |
          cowsay -f dragon "Run for cover, I am a DRAGON... RAWR" >> dragon.txt
          sleep 30

  build_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: slepp for 10 seconds
        run: sleep 10

      - name: Test file exists
        run: grep -i "dragon" dragon.txt
